always_for_in = true
conditional_to_if = true
format_docstrings = true
import_to_using=true
normalize_line_endings = "unix"
remove_extra_newlines = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
